[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "psipy"
version = "0.1.0"
description = "Pseudo-differential operator toolkit."
authors = [
    {name = "Philippe Billet", email = "ton@email.com"},
]
dependencies = [
    "numpy",
    "sympy",
    "scipy",
    "matplotlib",
    "librosa",
    "pywavelets",
    "ipython",
    'ipywidgets',
    "pillow",
]

[tool.pdoc]
modules = [
    "src.psiop",
    "src.solver",
    "src.physics",
    "src.geometry_1d",
    "src.geometry_2d",
    "src.stationary_phase",
    "src.hamiltonian_catalog",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
dev = [
    "black>=23.0",
    "flake8>=6.0",
    "isort>=5.0",
    "pylint>=3.0",
    "ruff>=0.1.0",
]
